# 项目相关配置
sp:
  # 名称
  name: sp
  # 版本
  version: 0.0.0
  # 版权年份
  copyrightYear: 2025
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/uploadPath，Linux配置 /home/uploadPath）
  profile: D:/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # Token配置
  token:
    # 是否启用Token验证
    enabled: false
    # Token过期时间（天），默认7天
    expireTime: 7

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8003
  port: 8003
  servlet:
    # 应用的访问路径
    context-path: /sp-api
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 企业微信配置
wechat:
  work:
    corpId: ww04fad852e91fd490
    agentId: 1000033
    secret: I31-B5clKayPf4vNl2bibhL1ia8x4cwIc884xK888Fc
    redirectUri: https://mo-stu-sys.org-assistant.com/sp-api/wechat/oauth/callback
    # 回调配置
    callback:
      token: YWhmCsbcN5dtvkN44t5aywaOxcxDWWMO
      encodingAesKey: 4C7hzSn2qFrO1hzMIJBY5iTL7UPKFZSUwmMX9TLF80D
      corpId: wpV9pWDAAA1nyVENSNCp5_m185fWSXEg
      permanentCode: I31-B5clKayPf4vNl2bibhL1ia8x4cwIc884xK888Fc

# 日志配置
logging:
  level:
    com.sp: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
  indexUrl: /index


# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 要用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/dist/,classpath:/static/
  mvc:
    throw-exception-if-no-handler-found: true
  autoconfigure:
    exclude: |
      org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration,
      org.springframework.boot.autoconfigure.web.ErrorPageRegistrarAutoConfiguration

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.sp.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 防止csrf攻击
csrf:
  # 过滤开关
  enabled: false
  # 白名单（多个用逗号分隔）
  whites: /druid

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true